### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Julian-A** [oleg-shilo/cs-script.npp#15]
I just installed CS-Script(version: 1.7.8.0) on my notepad++(version: 7.5.4).When, I run any code this error occurs in the output panel:

Error: Specified file could not be compiled.

System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.TraceCompilerInput(String cmdLine)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.Compile(CompilerParameters options, String compilerFullPath, String arguments, String& outputFile, Int32& nativeReturnValue)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.FromFileBatch(CompilerParameters options, String[] fileNames)
   at Microsoft.CodeDom.Providers.DotNetCompilerPlatform.Compiler.CompileAssemblyFromFileBatch(CompilerParameters options, String[] fileNames)
   at csscript.CSExecutor.CompileAssembly(ICodeCompiler compiler, CompilerParameters compilerParams, String[] filesToCompile)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()

This didn't happen in my old version of Notepad++(plugin manager pre-installed) with my old version of CS-Script(Don't remember the version).

**Comment by oleg-shilo** [comment]
It looks like your environment does not have the required .NET installed.
Installing .NET Framework 4.6 should fixed the problem.

If for whatever reason you don't want to update your .NET then you can always disable C# 7.0 support.

![image](https://user-images.githubusercontent.com/16729806/36552846-fcf98f10-184e-11e8-9080-823ff2e0890f.png)

**Comment by Julian-A** [comment]
This solved the problem, thank you very much.
