### ISSUE TITLE
Problems with NppAutomation in c# script

### ISSUE THREAD

**Issue by LlewellynJones** [oleg-shilo/cs-script.npp#43]
I'm having trouble creating a reference to NppAutomation.

Here's my code:

using System;
using System.Diagnostics;
using Npp=NppAutomation.Automation;

class Script
{
    [STAThread]
    static public void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
	Npp.OpenFile("blah");		
        Debug.WriteLine("Hello World!");
    }
}

Error: Specified file could not be compiled.

C:\XXXXX\Documents\C# Scripts\CycleEncoding.cs(4,11): error CS0246: The type or namespace name 'NppAutomation' could not be found (are you missing a using directive or an assembly reference?)

   at csscript.CSExecutor.ProcessCompilingResult(CompilerResults results, CompilerParameters compilerParams, ScriptParser parser, String scriptFileName, String assemblyFileName, String[] additionalDependencies)
   at csscript.CSExecutor.Compile(String scriptFileName)
   at csscript.CSExecutor.ExecuteImpl()

**Comment by oleg-shilo** [comment]
I am closing this one as we had a discussion with you in the NppAutomation repo.
